[project]
name = "equity"
version = "1.0.0"
description = "Equity Analyzer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=4.0.0",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "plotly>=5.17.0",
    "yfinance>=0.2.31",
]
